#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$kernel = new AppKernel('prod', false);
$application = new Application($kernel);
$application->run($input);
