<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    PhpBenchmarksSymfony\SmallOverloadBundle\SmallOverloadBundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload1Bundle\Overload1Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload2Bundle\Overload2Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload3Bundle\Overload3Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload4Bundle\Overload4Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload5Bundle\Overload5Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload6Bundle\Overload6Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload7Bundle\Overload7Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload8Bundle\Overload8Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload9Bundle\Overload9Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload10Bundle\Overload10Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload11Bundle\Overload11Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload12Bundle\Overload12Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload13Bundle\Overload13Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload14Bundle\Overload14Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload15Bundle\Overload15Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload16Bundle\Overload16Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload17Bundle\Overload17Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload18Bundle\Overload18Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload19Bundle\Overload19Bundle::class => ['all' => true],
    PhpBenchmarksSymfony\OverloadBundles\Overload20Bundle\Overload20Bundle::class => ['all' => true],
];
